basesite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('chat/', include('chat.urls')),
    path('', include('index.urls')),
    #path('index/', include('index.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('logout', LogoutView.as_view(), name="logout"),
]

chat/urls.py
# chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:room_name>/", views.room, name="room"),
]

chat/models.py
from django.db import models

# Create your models here.

chat/views.py
from django.shortcuts import render, redirect

def index(request):
    if request.method == "GET":
        return render(request, "chat/index.html")
    elif request.method == "POST":
        return redirect('chat:room', room_name=request.POST['room'])

def room(request, room_name):
    return render(request, "chat/room.html", {"room_name": room_name})

chat/templates/chat/base.html
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    
    {% load static %}
    <link rel="stylesheet" href="{% static 'index/mains.css' %}" />
</head>
<body>
    {% include 'index/navbar.html' %}
    <main>
        <div id="content">
            {% block content %}
            {% endblock %}        
        </div>
    </main>
    {% include 'index/footer.html' %}
</body>

chat/templates/chat/index.html
{# {% extends 'chat/base.html'%} #}
{# {% block content %} #}


{% load bootstrap5 %}     
{% bootstrap_css %}    
{% bootstrap_javascript %}
{# {% bootstrap_messages %} #}
<!-- chat/templates/chat/index.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'index/main.css' %}" />
</head>
<body>
    {% include "index/navbar.html" %}
    <main>
        <div id="content">
            <div class="d-flex flex-column align-items-center bd-highlight mb-3 text-light">
                <div class="card bg-dark text-center my-5">
                    <div class="card-header">
                        Welcome to the Study Buddy Chat!
                    </div>
                    <form action="{% url 'chat:index' %}" method="POST">{% csrf_token %}
                        <div class="card-body">
                            <input  name="room" type="text" class="form-control"
                                    placeholder="Enter chat name"
                                    aria-label="Chat room name"
                                    size="100" />
                        </div>
                        <div class="card-footer">
                            <button class="btn btn-outline-secondary" type="submit">
                                Join chat!
                            </button>
                        </div>
                    </form>
                </div>
            </div>            
            <!-- shadow content for testing the scroll -->
            {# {% for i in '0123456789'|make_list %} #}
            <!-- {# {% include "scroll-test.html" %} #} -->
            {# {% endfor %} #}
        </div>
    </main>
    {% include "index/footer.html" %}
</body>
</html>

chat/templates/chat/room.html
{% extends 'index/base.html'%}
{% load static %}
{% block content %}
<!-- chat/templates/chat/room.html -->
<title>Chat Room</title>
<div class="container">
    <div class="card bg-dark text-white">
        <div class="card-header">
            <div class="card-title">
                {{ room_name }}
            </div>
        </div>
        <div class="card-body" id="chat-log" style="height: 70vh;">
            <!-- Chat messages go here -->
        </div>
        </textarea>
        <div class="card-footer">
            <div class="input-group">
                <input id="chat-message-input" type="text" class="form-control" size="68" placeholder="Message" autofocus />
                <button class="btn btn-outline-secondary" type="button" id="chat-message-submit" value="Send">
                    <i class="fa-regular fa-paper-plane"></i>
                </button>
            </div>
        </div>
    </div>
</div>

<!-- Chat JS -->
{{ user.username|json_script:"user-name" }}
{{ room_name|json_script:"room-name" }}
<script>
    // chat room constants
    // // chat setup
    const room = JSON.parse(document.getElementById('room-name').textContent)
    const protocol = (window.location.protocol === "https:" ? "wss://" : "ws://")
    const socket = new WebSocket(`${protocol}${window.location.host}/ws/chat/${room}/`)
    // // chat elements/data
    const user = JSON.parse(document.getElementById('user-name').textContent)
    const chat_input_msg_text = document.querySelector('#chat-message-input')
    const chat_input_send_btn = document.querySelector('#chat-message-submit')
    // Chat events
    // // User sends message
    socket.onmessage = function (e) {
        // parse data
        const chat = JSON.parse(e.data)
        // log it        
        console.log(chat)
        // render it
        const msg_html = document.createElement("p")
        const text = document.createTextNode(`${chat.user} : ${chat.message}`)
        // add it to chat
        msg_html.appendChild(text)
        document.querySelector('#chat-log').append(msg_html)
    }
    // // User leaves chat or gets disconnected
    socket.onclose = (e) => console.error('Chat socket closed unexpectedly')
    // // User pressed <ENTER>
    window.addEventListener('keyup', (event) => {
        if (event.keyCode === 13)
            chat_input_send_btn.click()
    })
    // // User sent a message
    chat_input_send_btn.onclick = (e) => {
        const data = JSON.stringify({
            'user': user,
            'message': chat_input_msg_text.value
        })
        console.log(data)
        socket.send(data)
        chat_input_msg_text.value = ''
    }
</script>
{% endblock %}