basesite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('chat/', include('chat.urls')),
    path('', include('index.urls')),
    #path('index/', include('index.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('logout', LogoutView.as_view(), name="logout"),
]

chat/urls.py
# chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:room_name>/", views.room, name="room"),
]

index/urls.py
from django.urls import path

from . import views

app_name = 'index'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/edit', views.ProfileEditView.as_view(), name='editprofile'),
    path('profile/editBio/', views.EditBio, name='editbio'),
    path('profile/removeClass/', views.removeClass, name='removeClass'),
    path('profile/removeFriend/', views.removeFriend, name='removeFriend'),
    #path('profile/edit/confirm', views.confirmedit, name='confirmprofile'),
    #path('search/', views.SearchView.as_view(), name='search'),
    path('meetings/', views.MeetingsView.as_view(), name='meetings'),
    path('meetings/add', views.MeetingAddView.as_view(), name='addmeeting'),
    path('meetings/confirm/', views.addMeeting, name='confirmMeeting'),
    path('meetings/join/', views.joinMeeting, name='joinMeeting'),
    # Add classes
    # # Legacy
    path('search/', views.class_search, name='class_search'),
    path('search/results/', views.get_Results, name='class_results'),
    # # Newer
    # path('classes/search/', views.class_search_dummy, name='class_search_new'),
    # path('classes/results/', views.ClassResultsListView, name='class_results_new'),
    # # Success
    path('search/results/class_success/', views.class_success, name='class_success'),
    # Add users
    path('usersearch/', views.usersearch, name='usersearch'),
    path('usersearch/results/', views.UserResultsListView.as_view(), name='userresults'),
    path('usersearch/addedFriend/', views.addedFriend, name='addedFriend'),
    # path('view/', views.addedFriend, name='addedFriend'),
    
]

index/models.py
from django.contrib import admin
from django.db import models
from django.contrib.auth.models import User
from unittest.util import _MAX_LENGTH

class Course(models.Model):
    name = models.CharField(max_length=255)
    number = models.CharField(max_length=255)
    __str__ = lambda self: self.name

class UserInfo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE) # grabs data from user
    #add info here for classes through SIS API
    class_subject = models.CharField(max_length=5)
    class_number = models.CharField(max_length=5)
    class_section = models.CharField(max_length=5)
    #course = models.ForeignKey(Course, on_delete = models.CASCADE)
class UserBio(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.CharField(max_length=500, default="This is the default bio")
    degree = models.CharField(max_length=200, default="Unknown")
    year = models.CharField(max_length=50, default="Unknown")
    __str__ = lambda self: self.bio

class Friend(models.Model):
    # # User who made friend request
    adder = models.ForeignKey(User, on_delete=models.CASCADE)
    # # User who was looked up
    # user name
    addee_uid = models.CharField(max_length=150)
    # birth name 
    addee_nom = models.CharField(max_length=150)

class Meeting(models.Model):
    creation_date = models.DateTimeField('Date Created')
    title_text = models.CharField(max_length=40)
    owner_text = models.CharField(max_length=40)
    description_text = models.CharField(max_length=200)
    date = models.DateField('Date')
    start_date = models.TimeField('Start')
    end_date = models.TimeField('End')
class userMeeting(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    meeting = models.ForeignKey(Meeting, on_delete=models.CASCADE)
class Member(models.Model):
    meeting = models.ForeignKey(Meeting, on_delete=models.CASCADE)
    member_text = models.CharField(max_length=200)
    context_username = models.CharField(max_length=200, default="error")

index/forms.py
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.models import User
from .models import UserBio
from django import forms


class ChangeProfileForm(UserChangeForm):
    first_name = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class': 'form-control', 'size': '20'}))
    last_name = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class': 'form-control', 'size': '20'}))
    username = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class': 'form-control', 'size': '20'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'size': '20'}))
    password = None
    #password = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class': 'form-control', 'size': '20'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

class ChangeBioForm(forms.ModelForm):
    degree = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'class': 'form-control', 'size': '20'}))
    year = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control', 'size': '20'}))
    bio = forms.CharField(max_length=500, widget=forms.TextInput(attrs={'class': 'form-control', 'size': '20'}))
    class Meta:
        model = UserBio
        fields = ['degree', 'year', 'bio']

index/templates/index/addedClass.html
{% extends 'index/base.html'%}
{# {% load url %} #}
{% load static %}
<link rel="stylesheet" href="{% static 'index/style.css' %}">
	{% block content %}
	<!--User page HTML-->
	<body>
    	<div class="centered">
			<br>
    		<h1>Successfully Added Class</h1>
    		<br>
			
			<a href="{% url 'index:class_search' %}" class="btn btn-info">Add another course</a>
			<a href="{% url 'index:profile' %}" class="btn btn-info">View profile</a>
		</div>
	</body>
	{% endblock %}

index/templates/index/addedFriend.html
{% extends 'index/base.html'%}
{% load static %}
<link rel="stylesheet" href="{% static 'index/style.css' %}">
{% block content %}

<!--User page HTML-->

<body>
	<div class="centered">
		<br>
		<h1>Successfully Added Friend</h1>
		<br>
		<a href="{% url 'index:usersearch' %}" class="btn btn-info">Add Another Friend</a>
		<a href="{% url 'index:profile' %}" class="btn btn-info">View profile</a>
	</div>
</body>
{% endblock %}

index/templates/index/class-results.html
{% extends 'index/base.html'%}
{% block content %}
{% if response %}
<table class="table table-responsive table-striped table-dark">
  <thead>
    <tr>
      <th scope="col">Subject</th>
      <th scope="col">Number</th>
      <th scope="col">Course Section</th>
      <th scope="col">Instructor</th>
      <th scope="col">Email</th>
      <th scope="col">Description</th>
    </tr>
  </thead>
  <tbody>
    {% for i in response %}
    <tr>
      <td>{{i.subject}}</td>
      <td>{{i.catalog_number}}</td>
      <td>{{i.course_section}}</td>
      <td>{{i.instructor.name}}</td>
      <td>{{i.instructor.email}}</td>
      <td>{{i.description}}</td>
      <td>
        <form action="{% url 'index:class_success' %}" method="get">
          {% csrf_token %}
          {% load concat %}
          {% concat i.subject i.catalog_number i.course_section sep="-" as course_info %}
          <button name="thatClass" type="submit" class="btn btn-info" value="{{ course_info }}">
            Add Course
          </button>
        </form>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% else %}
<div class="card bg-dark text-white">
  <div class="card-header">
    <div class="card-title">
      <h1> Class Search Results </h1>
    </div>
  </div>
  <div class="card-body">
    <h3>There are no Classes that matched your search</h3>
  </div>
</div>
{% endif %}
{% endblock %}

index/templates/index/editbio.html
{% extends 'index/base.html'%}
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<link rel="stylesheet" href="{% static 'index/style.css' %}">
{% block content %}
{% load socialaccount %}
{% if user.is_authenticated %}
<div class="container">
    <div class="card bg-dark">
        <form method="post">{% csrf_token %}
            <div class="card-header bottom-border border-white">
                <div class="card-title">
                    <h3> Edit Bio </h3>
                </div>
            </div>
            <div class="card-body bottom-border border-white">
                <div class="container">

                    <div class="row">
                        <div class="col">
                            <label for="id_degree">Degree</label>
                        </div>
                        <div class="col">
                            <label for="id_year">Year</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <input type="text" name="degree" class="form-control" size="20" maxlength="200" placeholder="Degree" required id="id_degree" />
                        </div>
                        <div class="col">
                            <input type="text" name="year" class="form-control" size="20" maxlength="50" placeholder="Year" placeholder="Year" required id="id_year" />
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group">
                            <label for="id_bio">Introduce yourself</label>
                            <input type="text" name="bio" class="form-control" size="20" maxlength="500"
                                placeholder="Bio" required id="id_bio">
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer border-top border-white">
                <div class="container">
                    <div class="container">
                        <div class="d-flex flex-row justify-content-center">
                            <div class="row">
                                <div class="col mx-5">
                                    <button type="submit" value="Update" class="btn btn-success">
                                        <i class="fa-solid fa-check"></i>
                                    </button>
                                </div>
                                <div class="col mx-5">
                                    <a type="button" href="profile/" class="btn btn-danger">
                                        <i class="fa-solid fa-xmark"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% else %}
{% include 'index/signin-card.html' %}
{% endif %}
{% endblock content %}

index/templates/index/footer.html
<!-- https://getbootstrap.com/docs/5.2/examples/footers/ -->
<footer class="py-1 bg-dark">
    <div class="container">
        <ul class="nav justify-content-center border-bottom pb-1 mb-1">
            <li class="nav-item"><a href="/" class="nav-link px-2 text-muted">Home</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Terms of use</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Privacy Policy</a></li>
          </ul>
          <p class="text-center text-muted">Copyright &copy; 2022 Project B-06</p>      
    </div>
</footer>

index/templates/index/index.html
{% extends 'index/base.html'%}
{% load static %}
{% load socialaccount %}
{% block content %}
{% if user.is_authenticated %}
<div class="container">
  <div class="card bg-dark text-white">
    <div class="card-header mb-5">
      <div class="card-title">
        <div class="position-relative">
          <div class="position-absolute top-0 start-0">
            <h1> Meetings </h1>
          </div>
          <div class="position-absolute top-0 end-0  me-5 my-2">
            <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
              <div class="btn-group me-2" role="group" aria-label="Search">
                <a type="button" href="{% url 'index:meetings' %}" class="btn btn-secondary p-2">
                  <i class="fas fa-search fa-lg"></i>
                  Search
                </a>
              </div>
              <div class="btn-group ms-2" role="group" aria-label="Create">
                <a type="button" href="{% url 'index:addmeeting' %}" class="btn btn-secondary p-2">
                  <i class="fa-regular fa-calendar-plus fa-lg"></i>
                  Create
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="card-body">
      <table class="table table-dark">
        <thead>
          <tr>
            <th scope="col">Title</th>
            <th scope="col">Description</th>
            <th scope="col">Members</th>
            <th scope="col">Date</th>
            <th scope="col">Start</th>
            <th scope="col">End</th>
          </tr>  
        </thead>
        <tbody>
          {% if user.usermeeting_set.all %}
          {% for meeting in user.usermeeting_set.all %}
          <tr>
            <td>{{meeting.meeting.title_text}}</td>
            <td>{{meeting.meeting.description_text}}</td>
            <td>
              {% if meeting.meeting.member_set.all %}
              <ul style="list-style: none; padding-left: 0;">
                {% for member in meeting.meeting.member_set.all %}
                <li>{{ member.member_text }}</li>
                {% endfor %}
              </ul>
              {% else %}
              Empty
              {% endif %}
            </td>
            <td>{{meeting.meeting.date}}</td>
            <td>{{meeting.meeting.start_date}}</td>
            <td>{{meeting.meeting.end_date}}</td>
          </tr>
          {% endfor %}  
          {% else %}
          <tr>
            There are currently no meetings available.
          </tr>
          {% endif %}    
        </tbody>
      </table>
    </div>
  </div>
</div>
{% else %}
{% include 'index/signin-card.html' %}
{% endif %}
{% endblock %}

index/templates/index/profile.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Profile</title>
  {% load bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}

  {# {% bootstrap_messages %} #}

  {% load static %}
  <link rel="stylesheet" href="{% static 'index/main.css' %}" />
  <script src="https://kit.fontawesome.com/8e4d5ae4fe.js" crossorigin="anonymous"></script>
  <style>
    *::-webkit-scrollbar {
      width: 8px;
      height: 8px;
    }

    *::-webkit-scrollbar-thumb {
      background: #CCCCCC80;
    }
  </style>
</head>

<body>
  {% include 'navbar.html' %}
  <main>
    <div id="content" class="container">
      <div class="container">

        {% load socialaccount %}
        {% if user.is_authenticated %}
        <div class="card mb-5 text-center text-light bg-dark" style="height: 45vh; overflow-y: scroll;">
          <div class="container">
            <div class="card-header">
              <nav>
                <div class="nav nav-tabs card-header-tabs" id="nav-tab" role="tablist">
                  <button class="nav-link active" id="nav-profile-tab" data-bs-toggle="tab"
                    data-bs-target="#nav-profile" type="button" role="tab" aria-controls="nav-profile"
                    aria-selected="true">Profile</button>
                  <button class="nav-link" id="nav-bio-tab" data-bs-toggle="tab" data-bs-target="#nav-bio" type="button"
                    role="tab" aria-controls="nav-bio" aria-selected="false">Bio</button>
                  <button class="nav-link" id="nav-classes-tab" data-bs-toggle="tab" data-bs-target="#nav-classes"
                    type="button" role="tab" aria-controls="nav-classes" aria-selected="false">Classes</button>
                  <button class="nav-link" id="nav-friends-tab" data-bs-toggle="tab" data-bs-target="#nav-friends"
                    type="button" role="tab" aria-controls="nav-friends" aria-selected="false">Friends</button>
                </div>
              </nav>
            </div>
            <div class="card-body tab-content" id="nav-tabContent">
              <div class="tab-pane show active" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
                <table class="table table-responsive text-light bg-dark">
                  <thead>
                    <th>Profile</th>
                    <td>
                      <a class="btn btn-secondary" href="{% url 'index:editprofile' %}">
                        <i class="fa-solid fa-user-pen"></i>
                      </a>
                    </td>
                  </thead>
                  <tbody>
                    <tr>
                      <th scope="col">Name</th>
                      <td scope="col">{{ user.first_name }} {{ user.last_name }}</td>
                    </tr>
                    <tr>
                      <th scope="col">Username</th>
                      <td scope="col">{{ user.username }}</td>
                    </tr>
                    <tr>
                      <th scope="col">Email</th>
                      <td scope="col">{{ user.email }}</td>
                    </tr>
                  </tbody>
                </table>
              </div>
              <div class="tab-pane" id="nav-bio" role="tabpanel" aria-labelledby="nav-bio-tab">
                <table class="table table-responsive text-light bg-dark">
                  <thead>
                    <th scope="col">Bio</th>
                    <th scope="col">
                      <a href="{% url 'index:editbio' %}">
                        <button class="btn btn-secondary">
                          <i class="fa-solid fa-file-pen"></i>
                        </button>
                      </a>
                    </th>
                  </thead>
                  <tbody>
                    <tr>
                      <th scope="col">Major(s)/Minor(s)</th>
                      <td scope="col">{{ degree }}</td>
                    </tr>
                    <tr>
                      <th scope="col">Year</th>
                      <td scope="col">{{ year }}</td>
                    </tr>
                    <tr>
                      <td colspan="2"> {{ bio }} </td>
                    </tr>
                  </tbody>
                </table>
              </div>
              <div class="tab-pane" id="nav-classes" role="tabpanel" aria-labelledby="nav-classes-tab">
                <table class="table table-responsive caption-top text-light bg-dark">
                  <thead>
                    <tr>
                      <th scope="col" colspan="2">Classes</th>
                      <td scope="col" colspan="2">
                        <a class="btn btn-secondary" href="{% url 'index:class_search' %}">
                          <i class="fa-solid fa-cart-plus" style="transform: scaleX(-1) !important;"></i>
                        </a>
                      </td>
                    </tr>
                    {% if user.userinfo_set.all %}
                    <tr>
                      <th scope="col">Subject</th>
                      <th scope="col">Number</th>
                      <th scope="col">Section</th>
                      <th scope="col"></th>
                    </tr>
                  </thead>
                  <tbody>
                    <form action="{% url 'index:removeClass' %}" method="post" style="display: inline;">
                      {% csrf_token %}
                      {% for class in user.userinfo_set.all %}
                      <tr>
                        <td>{{ class.class_subject }}</td>
                        <td>{{ class.class_number }}</td>
                        <td>{{ class.class_section }}</td>
                        <td>
                          <button name="remove_class" type="submit" class="btn btn-danger" value="{{ class.id }}">
                            <i class="fa-solid fa-xmark"></i>
                          </button>
                        </td>
                      </tr>
                      {% endfor %}
                    </form>
                    {% else %}
                    <tr>
                      <h5> You haven't added any classes! Click the button to search for classes </h5>
                    </tr>
                    {% endif %}
                  </tbody>
                </table>
              </div>
              <div class="tab-pane" id="nav-friends" role="tabpanel" aria-labelledby="nav-friends-tab">
                
                <form action="{% url 'index:removeFriend' %}" method="POST">
                  {% csrf_token %}
                  <table class="table table-responsive text-light bg-dark">
                    <thead>
                      <tr>
                        <th scope="col">Friends</th>
                        <th scope="col">
                          <a href="{% url 'index:usersearch' %}" class="btn btn-secondary">
                            <i class="fa-solid fa-user-plus"></i>
                          </a>
                        </th>
                        <th scope="col"></th>
                      </tr>
                      {% if user.friend_set.all %}
                      <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Username</th>
                        <th scope="col"></th>
                      </tr>
                    </thead>
                    {% for friend in user.friend_set.all %}
                    <tr>
                      <td>{{ friend.addee_nom }}</td>
                      <td>{{ friend.addee_uid }}</td>
                      <td>
                        <button name="remove_friend" type="submit" class="btn btn-danger"
                          value="{{ friend.addee_uid }}">
                          <i class="fa-solid fa-xmark"></i>
                        </button>
                      </td>
                    </tr>
                    {% endfor %}
                    {% else %}
                    <tr>
                      <h5> Your friends list is empty, click the friends button to look up your friends </h5>
                    </tr>
                    {% endif %}
                  </table>
                </form>
              </div>
            </div>
          </div>
        </div>
        {% else %}
        {% include 'sigin-card.html' %}
        {% endif %}

      </div>
    </div>
  </main>
  {% include 'footer.html' %}
</body>

</html>

index/templates/index/view-profile.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Profile</title>
  {% load bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}

  {# {% bootstrap_messages %} #}

  {% load static %}
  <link rel="stylesheet" href="{% static 'index/main.css' %}" />
  <script src="https://kit.fontawesome.com/8e4d5ae4fe.js" crossorigin="anonymous"></script>
  <style>
    *::-webkit-scrollbar {
      width: 8px;
      height: 8px;
    }

    *::-webkit-scrollbar-thumb {
      background: #CCCCCC80;
    }
  </style>
</head>

<body>
  {% include 'navbar.html' %}
  <main>
    <div id="content" class="container">
      <div class="container">

        {% load socialaccount %}
        {% if user.is_authenticated %}
        {% if searched_user %}
        <div class="card mb-5 text-center text-light bg-dark" style="height: 45vh; overflow-y: scroll;">
          <div class="container">
            <div class="card-header">
              <nav>
                <div class="nav nav-tabs card-header-tabs" id="nav-tab" role="tablist">
                  <button class="nav-link active" id="nav-profile-tab" data-bs-toggle="tab"
                    data-bs-target="#nav-profile" type="button" role="tab" aria-controls="nav-profile"
                    aria-selected="true">Profile</button>
                  <button class="nav-link" id="nav-bio-tab" data-bs-toggle="tab" data-bs-target="#nav-bio" type="button"
                    role="tab" aria-controls="nav-bio" aria-selected="false">Bio</button>
                  <button class="nav-link" id="nav-classes-tab" data-bs-toggle="tab" data-bs-target="#nav-classes"
                    type="button" role="tab" aria-controls="nav-classes" aria-selected="false">Classes</button>
                  <button class="nav-link" id="nav-friends-tab" data-bs-toggle="tab" data-bs-target="#nav-friends"
                    type="button" role="tab" aria-controls="nav-friends" aria-selected="false">Friends</button>
                </div>
              </nav>
            </div>
            <div class="card-body tab-content" id="nav-tabContent">
              <div class="tab-pane show active" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
                <table class="table table-responsive text-light bg-dark">
                  <thead>
                    <th>Profile</th>
                    <td>
                      <a class="btn btn-secondary" href="{% url 'index:editprofile' %}">
                        <i class="fa-solid fa-user-pen"></i>
                      </a>
                    </td>
                  </thead>
                  <tbody>
                    <tr>
                      <th scope="col">Name</th>
                      <td scope="col">{{ searched_user.first_name }} {{ searched_user.last_name }}</td>
                    </tr>
                    <tr>
                      <th scope="col">Username</th>
                      <td scope="col">{{ searched_user.username }}</td>
                    </tr>
                    <tr>
                      <th scope="col">Email</th>
                      <td scope="col">{{ searched_user.email }}</td>
                    </tr>
                  </tbody>
                </table>
              </div>
              <div class="tab-pane" id="nav-bio" role="tabpanel" aria-labelledby="nav-bio-tab">
                <table class="table table-responsive text-light bg-dark">
                  <thead>
                    <th scope="col">Bio</th>
                    <th scope="col">
                      <a href="{% url 'index:editbio' %}">
                        <button class="btn btn-secondary">
                          <i class="fa-solid fa-file-pen"></i>
                        </button>
                      </a>
                    </th>
                  </thead>
                  <tbody>
                    <tr>
                      <th scope="col">Major(s)/Minor(s)</th>
                      <td scope="col">{{ degree }}</td>
                    </tr>
                    <tr>
                      <th scope="col">Year</th>
                      <td scope="col">{{ year }}</td>
                    </tr>
                    <tr>
                      <td colspan="2"> {{ bio }} </td>
                    </tr>
                  </tbody>
                </table>
              </div>
              <div class="tab-pane" id="nav-classes" role="tabpanel" aria-labelledby="nav-classes-tab">
                <table class="table table-responsive caption-top text-light bg-dark">
                  <thead>
                    <tr>
                      <th scope="col" colspan="2">Classes</th>
                      <td scope="col" colspan="2">
                        <a class="btn btn-secondary" href="{% url 'index:class_search' %}">
                          <i class="fa-solid fa-cart-plus" style="transform: scaleX(-1) !important;"></i>
                        </a>
                      </td>
                    </tr>
                    {% if searched_user.userinfo_set.all %}
                    <tr>
                      <th scope="col">Subject</th>
                      <th scope="col">Number</th>
                      <th scope="col">Section</th>
                      <th scope="col"></th>
                    </tr>
                  </thead>
                  <tbody>

                      {% csrf_token %}
                      {% for class in searched_user.userinfo_set.all %}
                      <tr>
                        <td>{{ class.class_subject }}</td>
                        <td>{{ class.class_number }}</td>
                        <td>{{ class.class_section }}</td>
                        <td>
                          <button name="remove_class" type="submit" class="btn btn-danger" value="{{ class.id }}">
                            <i class="fa-solid fa-xmark"></i>
                          </button>
                        </td>
                      </tr>
                      {% endfor %}

                    {% else %}
                    <tr>
                      <h5> You haven't added any classes! Click the button to search for classes </h5>
                    </tr>
                    {% endif %}
                  </tbody>
                </table>
              </div>
              <div class="tab-pane" id="nav-friends" role="tabpanel" aria-labelledby="nav-friends-tab">
                
                  <table class="table table-responsive text-light bg-dark">
                    <thead>
                      <tr>
                        <th scope="col">Friends</th>
                        <th scope="col">
                          <a href="{% url 'index:usersearch' %}" class="btn btn-secondary">
                            <i class="fa-solid fa-user-plus"></i>
                          </a>
                        </th>
                        <th scope="col"></th>
                      </tr>
                      {% if searched_user.friend_set.all %}
                      <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Username</th>
                        <th scope="col"></th>
                      </tr>
                    </thead>
                    {% for friend in searched_user.friend_set.all %}
                    <tr>
                      <td>{{ friend.addee_nom }}</td>
                      <td>{{ friend.addee_uid }}</td>
                      <td>
                        <button name="remove_friend" type="submit" class="btn btn-danger"
                          value="{{ friend.addee_uid }}">
                          <i class="fa-solid fa-xmark"></i>
                        </button>
                      </td>
                    </tr>
                    {% endfor %}
                    {% else %}
                    <tr>
                      <h5> Your friends list is empty, click the friends button to look up your friends </h5>
                    </tr>
                    {% endif %}
                  </table>

                </div>
            </div>
          </div>
        </div>
        {% else %}
        <div class="card bg-dark text-white">
            <div class="card-body">
                No user exists
            </div>
        </div>
        {% else %}
        {% include 'sigin-card.html' %}
        {% endif %}

      </div>
    </div>
  </main>
  {% include 'footer.html' %}
</body>

</html>